name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: hello world 출력!!
      run: echo Hello, world!
    - name: 디렉토리출력!!
      run: ls -asl
    - name: 파이썬 출력!!
      run: python -V
    - name: 노드 출력!!
      run: node -v
    - uses: actions/checkout@v2
    - name: 파이썬 실행!!
      run: python test.py
